CREATE TABLE public.customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name TEXT NOT NULL,
    email TEXT UNIQUE,
    total_purchases NUMERIC DEFAULT 0,
    monthly_charges NUMERIC DEFAULT 0,
    contract_type TEXT,
    churn BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);